---
- name: Configure Aruba Switch
  hosts: aruba_switch
  gather_facts: no
  tasks:
    - name: Configurable backup path
      community.network.aruba_config:
        backup: true
        backup_options:
          filename: backup.cfg
          dir_path: /home/user
