---
- name: Backup Aruba Switch Configuration
  hosts: aruba_switch
  gather_facts: no
  tasks:
    - name: Fetch running configuration
      community.network.aruba_command:
        commands:
          - show running-config
        wait_for: result[0] contains "hostname"
      register: config_output

    - name: Save running configuration to file
      copy:
        content: "{{ config_output.stdout | join('\n') }}"
        dest: "/path/to/backup/folder/aruba_config_{{ ansible_date_time.date }}.txt"
