---
- hosts: Backup aruba
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Backup running configuration
      community.network.aruba_config:
        backup: true
        backup_options:
          filename: backup.cfg
          dir_path: /home/user
