---
- hosts: all
  tasks:
    - name: Backup switch configuration
      aruba_config:
        commands:
          - "show running-config"
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}_{{ ansible_date_time.date }}.cfg"
          dir: /backups

    - name: Save backup file to AWX
      ansible.builtin.copy:
        src: /backups/{{ inventory_hostname }}_{{ ansible_date_time.date }}.cfg"
        dest: /path/to/awx/backups/{{ inventory_hostname }}/
